### ISSUE TITLE
events

### ISSUE THREAD

**Issue by smudge202** [smudge202/clean-living#9]
The engine, as per Issue #6 and PR #8, supports time events, but there is currently no support for arbitrary events defined by a game.

I think we need to expand the engine's capabilities to support these abitrary events.

**Comment by mattridgway** [comment]
Im thinking rather than subscribe to each individual component (like health, movement) you subscribe to the engine -> it will give you updates to your perspective which you maintain - or you can request your entire perspective. This way the composition will decide what components are available these components then push the updates out through the engine. different implementations of each component can decide what they subscribe to - eg. zombie mode - doesn't care about thirst, so doesn't subscribe to it, so those updates don't come out of the engine

**Comment by smudge202** [comment]
I agree, which is what I implemented in PR #8 :)  Subscriptions are made to the engine itself, as are associated publications.  That what you had in mind?

Components like Thirst are completely independent of other components.  Going to have a crack at the first game component(s) today to see how that shapes up.
